# Generated by Django 4.1.2 on 2022-10-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmesA24Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('diretor', models.CharField(max_length=255)),
                ('lancamento', models.DateTimeField()),
            ],
        ),
    ]
