# Generated by Django 4.1.2 on 2022-10-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmesa24model',
            name='lancamento',
            field=models.DateField(),
        ),
    ]
