# Generated by Django 4.1.2 on 2022-10-20 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_filmesa24model_lancamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmesa24model',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.RenameField(
            model_name='filmesa24model',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.CreateModel(
            name='ComentariosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True, default='', max_length=255)),
                ('data', models.DateTimeField()),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.filmesa24model')),
            ],
        ),
    ]
