# Generated by Django 4.1.2 on 2022-10-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comentariosmodel_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariosmodel',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='filmesa24model',
            options={'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
    ]
