# Generated by Django 4.1.2 on 2022-11-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_comentariosmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentariosmodel',
            options={'ordering': ['id'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='filmesa24model',
            options={'ordering': ['id'], 'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
    ]
